# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2gV8n1hwiYoJSEiby7aUuHjtqKGvWhi
"""

import numpy as np
from scipy.io import wavfile

def generate_hex_mem(wav_filename, mem_filename):
    # 1. Read the audio file
    # Note: Make sure your input wav is 16-bit PCM!
    sample_rate, data = wavfile.read(wav_filename)

    print(f"Loaded {wav_filename} at {sample_rate} Hz")

    # 2. Convert to Mono (if the song is stereo)
    if len(data.shape) == 2:
        print("Stereo audio detected. Converting to Mono...")
        data = data[:, 0] # Keep only the left channel

    # 3. Truncate to exactly 3 seconds (to match your 128-frame buffer)
    # 3 seconds * 44100 samples/sec = 132,300 samples
    max_samples = int(3.0 * sample_rate)
    if len(data) > max_samples:
        data = data[:max_samples]

    # 4. Write to the Verilog .mem file
    with open(mem_filename, 'w') as f:
        for sample in data:
            # Convert standard integers to 16-bit Two's Complement Hexadecimal.
            # The '& 0xFFFF' is a bitwise trick that cleanly converts negative
            # audio values into correct Verilog-readable hex strings.
            hex_val = f"{sample & 0xFFFF:04X}\n"
            f.write(hex_val)

    print(f"Successfully wrote {len(data)} samples to {mem_filename}")

# Run the function
generate_hex_mem('my_test_song.wav', 'song_data.mem')